# Site wide configuration

title: Bipolar Artists Union
description: "Bipolar Artists Union Website."
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //bipolarartist.org/

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap

# please leave this value set to true. The way we use this blog, we publish events in the future regularly.
future: true

# Site owner
owner:
  name: Curt White
  web: https://bipolarartist.org
  email: curtpw@gmail.com
  twitter: 
  bio: "Curt is an artist, engineer and mental health activist."
  avatar: logo-avatar-160x160.png # 160x160 px image for author byline
  google:
    plus: 
    ad-client: 
    ad-slot: 
  disqus-shortname: 


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
